// src/itemLists.js

const CATEGORIES = {
    '1H_WEAPON': [
        'MAIN_SWORD', 'MAIN_AXE', 'MAIN_MACE', 'MAIN_HAMMER', 'MAIN_SPEAR', 
        'MAIN_HOLYSTAFF', 'MAIN_FIRESTAFF', 'MAIN_ARCANESTAFF', 'MAIN_FROSTSTAFF', 
        'MAIN_CURSEDSTAFF', 'MAIN_NATURESTAFF', 'MAIN_DAGGER', 'MAIN_QSTAFF'
    ],
    '2H_WEAPON': [
        '2H_CLAYMORE', '2H_HALBERD', '2H_POLEHAMMER', '2H_GLAIVE', '2H_BOW', 
        '2H_CROSSBOW', '2H_CURSEDSTAFF', '2H_FIRESTAFF', '2H_FROSTSTAFF', 
        '2H_ARCANESTAFF', '2H_HOLYSTAFF', '2H_NATURESTAFF', '2H_DAGGERPAIR', 
        '2H_QUARTERSTAFF', '2H_IRONGAUNTLETS', '2H_DUALSWORDS'
    ],
    'ARMOR': [
        'ARMOR_PLATE_SET1', 'ARMOR_PLATE_SET2', 'ARMOR_PLATE_SET3',
        'ARMOR_LEATHER_SET1', 'ARMOR_LEATHER_SET2', 'ARMOR_LEATHER_SET3',
        'ARMOR_CLOTH_SET1', 'ARMOR_CLOTH_SET2', 'ARMOR_CLOTH_SET3'
    ],
    'OFF_HAND': [
        'OFF_BOOK', 'OFF_SHIELD', 'OFF_TORCH', 'OFF_HORN', 'OFF_ORB', 'OFF_TOTEM'
    ]
};

module.exports = { CATEGORIES };